name: Build C/C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    container: centos:7

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16

    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3

    - name: Fix CentOS 7 EOL repositories
      run: |
        sed -i.bak 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i.bak 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

    - name: Update cache
      run: yes | yum -y --assumeyes makecache

    - name: Install build dependencies
      run: yes | yum -y --assumeyes install @'Development Tools' glibc-devel.i686 libgcc.i686 libstdc++-devel.i686 libgcc.i686 libstdc++-static.i686 wget

    - name: Run build
      working-directory: ./AccuracyFix
      run: |
        export CPATH=$CPATH:/usr/include/c++/4.8.5/i686-redhat-linux
        make
    
    - name: Make Accuracy Fix path
      run: mkdir -p publish/addons/accuracyfix/dlls

    - name: Make Accuracy Fix path
      run: mv ./AccuracyFix/Release/accuracyfix_mm.so publish/addons/accuracyfix/dlls
      
    - name: Move settings file to folder
      run: mv ./cstrike/addons/accuracyfix/accuracyfix.cfg publish/addons/accuracyfix/accuracyfix.cfg

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux32
        path: publish/*
        
  windows:
    name: Windows Build
    runs-on: windows-latest
      
    env:
      SOLUTION_FILE_PATH: .
      BUILD_CONFIGURATION: Release
  
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Run Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Move release file to publish
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        # Make publish directory
        mkdir publish\addons\accuracyfix\dlls

        # Move released dll to publish
        move ${{env.BUILD_CONFIGURATION}}\*.dll publish\addons\accuracyfix\dlls

        # Move settings file to folder
        mv ${{env.SOLUTION_FILE_PATH}}\cstrike\addons\accuracyfix\accuracyfix.cfg publish\addons\accuracyfix\accuracyfix.cfg

    - name: Deploy artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win32
        path: publish/*
